import 'dart:async';

import 'package:audioplayers/audioplayers.dart';

/// The cues the Wrapped story plays, one per reveal.
///
/// The files are generated by `tool/generate_wrapped_sounds.py` rather than
/// licensed — see that script for the sound design and for how to retune them.
enum WrappedCue {
  /// Panel 1 — the low bloom the story opens on.
  open('wrapped_open.wav'),

  /// Panel 2 — three notes climbing under the headline number.
  count('wrapped_count.wav'),

  /// One subject bar sliding in, or a month arrow.
  tick('wrapped_tick.wav'),

  /// Panel 4 — the two-note compliment.
  chime('wrapped_chime.wav'),

  /// Panel 5 — the card.
  finish('wrapped_finish.wav');

  const WrappedCue(this.file);

  final String file;

  /// `AssetSource` resolves under `assets/` via audioplayers' own prefix, so
  /// this is deliberately not the full asset path.
  String get path => 'sounds/$file';
}

/// Plays the Wrapped cues.
///
/// One [AudioPlayer] per cue, each with its source set once up front. Sharing a
/// single player would mean calling `setSource` on every fire — which
/// re-prepares the asset and waits for the platform to report it ready, the
/// latency audioplayers' own documentation tells you to avoid — and each fire
/// would cut off whatever was already sounding, so a bar tick would silence the
/// arpeggio it is meant to land under.
///
/// Nothing here may throw or block the UI. A cue that fails to load or play is
/// simply silent: the sound is decoration, and a student on a phone with no
/// working audio route still gets the whole story.
class WrappedAudio {
  WrappedAudio({required bool enabled}) : _enabled = enabled;

  /// The cues ride the media route, and never take audio focus.
  ///
  /// This first shipped as a sonification usage on Android and the `ambient`
  /// category on iOS — the correct manners for a UI blip, and the reason the
  /// story shipped silent. Android maps that usage onto the system stream,
  /// which is muted whenever the ringer is; `ambient` is silenced by the iOS
  /// mute switch. Between them that is most phones in a student's hand, and
  /// both were mute while the media volume they had up for videos did nothing.
  ///
  /// A Wrapped's sound is part of what the student came to see, not a
  /// notification about it, so it belongs on the slider they already turned up.
  /// Good manners are kept where they cost nothing: [AndroidAudioFocus.none]
  /// and `mixWithOthers` mean nothing already playing is paused or ducked, and
  /// the screen carries its own mute button for anyone who wants silence.
  static final AudioContext _context = AudioContext(
    android: const AudioContextAndroid(
      contentType: AndroidContentType.music,
      usageType: AndroidUsageType.media,
      audioFocus: AndroidAudioFocus.none,
    ),
    iOS: AudioContextIOS(
      // The one output category that survives the mute switch. `mixWithOthers`
      // is what keeps it from interrupting anything else the way `playback`
      // would on its own.
      category: AVAudioSessionCategory.playback,
      options: const {AVAudioSessionOptions.mixWithOthers},
    ),
  );

  final _players = <WrappedCue, AudioPlayer>{};

  /// Ticks scheduled but not yet fired, so they can be called off when the
  /// student swipes away mid-stagger.
  final _pending = <Timer>[];

  Future<void>? _loading;
  bool _enabled;
  bool _disposed = false;

  bool get enabled => _enabled;

  /// Silences what is already sounding on the way down, so muting takes effect
  /// now rather than from the next panel.
  set enabled(bool value) {
    if (_enabled == value) return;
    _enabled = value;
    if (!value) _silence();
  }

  /// Loads every cue. Idempotent — later calls await the first one's work.
  Future<void> load() => _loading ??= _load();

  Future<void> _load() async {
    for (final cue in WrappedCue.values) {
      if (_disposed) return;
      try {
        final player = AudioPlayer();
        // Left on the default MediaPlayer mode. Low latency mode is SoundPool,
        // which loads on its own thread with no error path at all: a cue it
        // cannot decode never reports anything, it simply never becomes
        // playable, and there is nothing to catch or log. These are preloaded
        // and none is over two seconds, so the head start it would buy is not
        // worth a failure mode that cannot be seen from here.
        //
        // `stop` and not `release`, or the decoded buffer is thrown away after
        // every play and the next tick pays to load it again.
        await player.setReleaseMode(ReleaseMode.stop);
        await player.setAudioContext(_context);
        await player.setSource(AssetSource(cue.path));

        if (_disposed) {
          await player.dispose();
          return;
        }
        _players[cue] = player;
      } catch (_) {
        // This one cue stays silent; the rest of the story keeps its sound.
      }
    }
  }

  /// Fires [cue], calling off anything still queued behind it.
  void play(WrappedCue cue) {
    _cancelPending();
    unawaited(_fire(cue));
  }

  /// One tick per subject bar, on the clock the bars themselves animate to.
  ///
  /// [first] is when the first bar lands and [gap] the spacing between them —
  /// passed in rather than known here so the sound cannot drift out of step
  /// with the picture when the animation is retimed.
  void playTicks({
    required int count,
    required Duration first,
    required Duration gap,
  }) {
    _cancelPending();
    for (var i = 0; i < count; i++) {
      _pending.add(Timer(first + gap * i, () => unawaited(_fire(WrappedCue.tick))));
    }
  }

  Future<void> _fire(WrappedCue cue) async {
    if (!_enabled || _disposed) return;
    await load();

    final player = _players[cue];
    // Re-checked after the await: muting or leaving the screen while the load
    // was still running must not be overtaken by a cue queued before it.
    if (player == null || !_enabled || _disposed) return;

    try {
      // stop() rewinds, resume() plays from the top. Together they retrigger a
      // preloaded source without paying to set it again.
      await player.stop();
      await player.resume();
    } catch (_) {
      // Silence beats a crash on a screen whose whole job is a nice moment.
    }
  }

  void _cancelPending() {
    for (final timer in _pending) {
      timer.cancel();
    }
    _pending.clear();
  }

  void _silence() {
    _cancelPending();
    for (final player in _players.values) {
      unawaited(_quiet(player));
    }
  }

  static Future<void> _quiet(AudioPlayer player) async {
    try {
      await player.stop();
    } catch (_) {
      // Already stopped, or the platform player is gone. Either way: quiet.
    }
  }

  Future<void> dispose() async {
    _disposed = true;
    _cancelPending();
    for (final player in _players.values) {
      try {
        await player.dispose();
      } catch (_) {
        // Nothing useful left to do with a player that will not let go.
      }
    }
    _players.clear();
  }
}
