// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7cackZaRcuLLDcsS_1Ttutowv8DHkypE',
    appId: '1:267993935158:android:942314ed079c8786bc9797',
    messagingSenderId: '267993935158',
    projectId: 'nltc-online',
    databaseURL: 'https://nltc-online-default-rtdb.firebaseio.com',
    storageBucket: 'nltc-online.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpiDKgeUD1bY4d4O6pU7zZbxSggK4zWs',
    appId: '1:267993935158:ios:b1611e12c7f8bb42bc9797',
    messagingSenderId: '267993935158',
    projectId: 'nltc-online',
    databaseURL: 'https://nltc-online-default-rtdb.firebaseio.com',
    storageBucket: 'nltc-online.firebasestorage.app',
    iosClientId: '267993935158-6alrdtj8pcanc3bfu1dq8a6mgqf0l1u0.apps.googleusercontent.com',
    iosBundleId: 'ng.com.nltc',
  );
}
