import 'dart:convert';

import 'question.dart';

/// Where a finished attempt is in its journey to the server.
enum SyncState {
  /// Graded on-device, not yet accepted by the backend.
  pending,

  /// Backend acknowledged it; XP has been awarded.
  synced,

  /// Repeatedly rejected — kept on device so the score is never silently lost.
  failed,
}

/// One completed CBT attempt.
///
/// Attempts are graded entirely on-device (the correct answer ships with the
/// question, exactly as it does on the web) so a student with no signal still
/// gets an immediate score. The attempt is then queued for sync; [id] is
/// generated by the client and sent as the idempotency key so a replayed
/// submission can never award XP twice.
class ExamAttempt {
  const ExamAttempt({
    required this.id,
    required this.subject,
    required this.exam,
    required this.questionIds,
    required this.answers,
    required this.correct,
    required this.total,
    required this.durationSeconds,
    required this.submittedAt,
    this.topic,
    this.syncState = SyncState.pending,
    this.syncAttempts = 0,
  });

  /// Client-generated, stable across retries — the idempotency key.
  final String id;

  final String subject;
  final String exam;
  final String? topic;

  /// The questions served, in the order shown.
  final List<String> questionIds;

  /// questionId → chosen option key. Skipped questions are simply absent.
  final Map<String, String> answers;

  final int correct;
  final int total;
  final int durationSeconds;
  final DateTime submittedAt;

  final SyncState syncState;
  final int syncAttempts;

  /// Percentage, rounded to one decimal — matches the backend's formula so a
  /// synced attempt shows the same number the server stored.
  double get score =>
      total == 0 ? 0 : (correct / total * 100 * 10).round() / 10;

  int get answeredCount => answers.length;
  int get skippedCount => total - answeredCount;

  /// Grades a finished attempt against the questions the student actually saw.
  factory ExamAttempt.grade({
    required String id,
    required String subject,
    required String exam,
    String? topic,
    required List<Question> questions,
    required Map<String, String> answers,
    required int durationSeconds,
    DateTime? submittedAt,
  }) {
    var correct = 0;
    for (final q in questions) {
      if (q.isCorrect(answers[q.id])) correct++;
    }
    return ExamAttempt(
      id: id,
      subject: subject,
      exam: exam,
      topic: topic,
      questionIds: questions.map((q) => q.id).toList(),
      answers: answers,
      correct: correct,
      total: questions.length,
      durationSeconds: durationSeconds,
      submittedAt: submittedAt ?? DateTime.now(),
    );
  }

  ExamAttempt copyWith({SyncState? syncState, int? syncAttempts}) =>
      ExamAttempt(
        id: id,
        subject: subject,
        exam: exam,
        topic: topic,
        questionIds: questionIds,
        answers: answers,
        correct: correct,
        total: total,
        durationSeconds: durationSeconds,
        submittedAt: submittedAt,
        syncState: syncState ?? this.syncState,
        syncAttempts: syncAttempts ?? this.syncAttempts,
      );

  Map<String, Object?> toRow() => {
        'id': id,
        'subject': subject,
        'exam': exam,
        'topic': topic,
        'question_ids': jsonEncode(questionIds),
        'answers': jsonEncode(answers),
        'correct': correct,
        'total': total,
        'duration_seconds': durationSeconds,
        'submitted_at': submittedAt.millisecondsSinceEpoch,
        'sync_state': syncState.name,
        'sync_attempts': syncAttempts,
      };

  factory ExamAttempt.fromRow(Map<String, Object?> r) => ExamAttempt(
        id: r['id'] as String,
        subject: r['subject'] as String? ?? '',
        exam: r['exam'] as String? ?? '',
        topic: r['topic'] as String?,
        questionIds: _decodeList(r['question_ids'] as String?),
        answers: _decodeMap(r['answers'] as String?),
        correct: (r['correct'] as num?)?.toInt() ?? 0,
        total: (r['total'] as num?)?.toInt() ?? 0,
        durationSeconds: (r['duration_seconds'] as num?)?.toInt() ?? 0,
        submittedAt: DateTime.fromMillisecondsSinceEpoch(
          (r['submitted_at'] as num?)?.toInt() ?? 0,
        ),
        syncState: SyncState.values.firstWhere(
          (s) => s.name == r['sync_state'],
          orElse: () => SyncState.pending,
        ),
        syncAttempts: (r['sync_attempts'] as num?)?.toInt() ?? 0,
      );

  /// The body posted to `/api/gamification/cbt-session`.
  Map<String, dynamic> toSyncPayload() => {
        'clientAttemptId': id,
        'subject': subject,
        'exam': exam,
        'score': score,
        'correct': correct,
        'total': total,
        if (topic != null) 'topic': topic,
      };

  static List<String> _decodeList(String? raw) {
    if (raw == null || raw.isEmpty) return const [];
    try {
      final d = jsonDecode(raw);
      if (d is List) return d.map((e) => '$e').toList();
    } catch (_) {/* corrupt row — treat as empty */}
    return const [];
  }

  static Map<String, String> _decodeMap(String? raw) {
    if (raw == null || raw.isEmpty) return const {};
    try {
      final d = jsonDecode(raw);
      if (d is Map) return d.map((k, v) => MapEntry('$k', '$v'));
    } catch (_) {/* corrupt row — treat as empty */}
    return const {};
  }
}
